// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor_ext.proto

#include "descriptor_ext.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ext {
PROTOBUF_CONSTEXPR Descriptor::Descriptor(
    ::_pbi::ConstantInitialized)
  : descriptor_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct DescriptorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DescriptorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DescriptorDefaultTypeInternal() {}
  union {
    Descriptor _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DescriptorDefaultTypeInternal _Descriptor_default_instance_;
}  // namespace ext
static ::_pb::Metadata file_level_metadata_descriptor_5fext_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_descriptor_5fext_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_descriptor_5fext_2eproto = nullptr;

const uint32_t TableStruct_descriptor_5fext_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ext::Descriptor, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ext::Descriptor, descriptor_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ext::Descriptor)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ext::_Descriptor_default_instance_._instance,
};

const char descriptor_table_protodef_descriptor_5fext_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024descriptor_ext.proto\022\003ext\" \n\nDescripto"
  "r\022\022\n\ndescriptor\030\001 \001(\014b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_descriptor_5fext_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_descriptor_5fext_2eproto = {
    false, false, 69, descriptor_table_protodef_descriptor_5fext_2eproto,
    "descriptor_ext.proto",
    &descriptor_table_descriptor_5fext_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_descriptor_5fext_2eproto::offsets,
    file_level_metadata_descriptor_5fext_2eproto, file_level_enum_descriptors_descriptor_5fext_2eproto,
    file_level_service_descriptors_descriptor_5fext_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_descriptor_5fext_2eproto_getter() {
  return &descriptor_table_descriptor_5fext_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_descriptor_5fext_2eproto(&descriptor_table_descriptor_5fext_2eproto);
namespace ext {

// ===================================================================

class Descriptor::_Internal {
 public:
};

Descriptor::Descriptor(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:ext.Descriptor)
}
Descriptor::Descriptor(const Descriptor& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  descriptor_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    descriptor_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_descriptor().empty()) {
    descriptor_.Set(from._internal_descriptor(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ext.Descriptor)
}

inline void Descriptor::SharedCtor() {
descriptor_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  descriptor_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Descriptor::~Descriptor() {
  // @@protoc_insertion_point(destructor:ext.Descriptor)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Descriptor::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  descriptor_.Destroy();
}

void Descriptor::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Descriptor::Clear() {
// @@protoc_insertion_point(message_clear_start:ext.Descriptor)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  descriptor_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Descriptor::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bytes descriptor = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_descriptor();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Descriptor::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ext.Descriptor)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes descriptor = 1;
  if (!this->_internal_descriptor().empty()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_descriptor(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ext.Descriptor)
  return target;
}

size_t Descriptor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ext.Descriptor)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes descriptor = 1;
  if (!this->_internal_descriptor().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_descriptor());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Descriptor::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Descriptor::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Descriptor::GetClassData() const { return &_class_data_; }

void Descriptor::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Descriptor *>(to)->MergeFrom(
      static_cast<const Descriptor &>(from));
}


void Descriptor::MergeFrom(const Descriptor& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ext.Descriptor)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_descriptor().empty()) {
    _internal_set_descriptor(from._internal_descriptor());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Descriptor::CopyFrom(const Descriptor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ext.Descriptor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Descriptor::IsInitialized() const {
  return true;
}

void Descriptor::InternalSwap(Descriptor* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &descriptor_, lhs_arena,
      &other->descriptor_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Descriptor::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_descriptor_5fext_2eproto_getter, &descriptor_table_descriptor_5fext_2eproto_once,
      file_level_metadata_descriptor_5fext_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ext
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ext::Descriptor*
Arena::CreateMaybeMessage< ::ext::Descriptor >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ext::Descriptor >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
