// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: certificate.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_certificate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_certificate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_certificate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_certificate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_certificate_2eproto;
namespace legacy_pb {
class Certificate;
struct CertificateDefaultTypeInternal;
extern CertificateDefaultTypeInternal _Certificate_default_instance_;
}  // namespace legacy_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::legacy_pb::Certificate* Arena::CreateMaybeMessage<::legacy_pb::Certificate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace legacy_pb {

enum Certificate_Version : int {
  Certificate_Version_UNKNOWN_VERSION = 0,
  Certificate_Version__0_0_1 = 1
};
bool Certificate_Version_IsValid(int value);
constexpr Certificate_Version Certificate_Version_Version_MIN = Certificate_Version_UNKNOWN_VERSION;
constexpr Certificate_Version Certificate_Version_Version_MAX = Certificate_Version__0_0_1;
constexpr int Certificate_Version_Version_ARRAYSIZE = Certificate_Version_Version_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Certificate_Version_descriptor();
template<typename T>
inline const std::string& Certificate_Version_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Certificate_Version>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Certificate_Version_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Certificate_Version_descriptor(), enum_t_value);
}
inline bool Certificate_Version_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Certificate_Version* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Certificate_Version>(
    Certificate_Version_descriptor(), name, value);
}
enum KeyType : int {
  UNKNOWN_PUBLIC_KEY_TYPE = 0,
  NIST256p = 1,
  NIST384p = 2,
  SECP256k1 = 3
};
bool KeyType_IsValid(int value);
constexpr KeyType KeyType_MIN = UNKNOWN_PUBLIC_KEY_TYPE;
constexpr KeyType KeyType_MAX = SECP256k1;
constexpr int KeyType_ARRAYSIZE = KeyType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* KeyType_descriptor();
template<typename T>
inline const std::string& KeyType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, KeyType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function KeyType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    KeyType_descriptor(), enum_t_value);
}
inline bool KeyType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, KeyType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<KeyType>(
    KeyType_descriptor(), name, value);
}
// ===================================================================

class Certificate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:legacy_pb.Certificate) */ {
 public:
  inline Certificate() : Certificate(nullptr) {}
  ~Certificate() override;
  explicit PROTOBUF_CONSTEXPR Certificate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Certificate(const Certificate& from);
  Certificate(Certificate&& from) noexcept
    : Certificate() {
    *this = ::std::move(from);
  }

  inline Certificate& operator=(const Certificate& from) {
    CopyFrom(from);
    return *this;
  }
  inline Certificate& operator=(Certificate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Certificate& default_instance() {
    return *internal_default_instance();
  }
  static inline const Certificate* internal_default_instance() {
    return reinterpret_cast<const Certificate*>(
               &_Certificate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Certificate& a, Certificate& b) {
    a.Swap(&b);
  }
  inline void Swap(Certificate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Certificate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Certificate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Certificate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Certificate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Certificate& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Certificate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "legacy_pb.Certificate";
  }
  protected:
  explicit Certificate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Certificate_Version Version;
  static constexpr Version UNKNOWN_VERSION =
    Certificate_Version_UNKNOWN_VERSION;
  static constexpr Version _0_0_1 =
    Certificate_Version__0_0_1;
  static inline bool Version_IsValid(int value) {
    return Certificate_Version_IsValid(value);
  }
  static constexpr Version Version_MIN =
    Certificate_Version_Version_MIN;
  static constexpr Version Version_MAX =
    Certificate_Version_Version_MAX;
  static constexpr int Version_ARRAYSIZE =
    Certificate_Version_Version_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Version_descriptor() {
    return Certificate_Version_descriptor();
  }
  template<typename T>
  static inline const std::string& Version_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Version>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Version_Name.");
    return Certificate_Version_Name(enum_t_value);
  }
  static inline bool Version_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Version* value) {
    return Certificate_Version_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPublicKeyFieldNumber = 4,
    kVersionFieldNumber = 1,
    kKeyTypeFieldNumber = 2,
  };
  // required bytes publicKey = 4;
  bool has_publickey() const;
  private:
  bool _internal_has_publickey() const;
  public:
  void clear_publickey();
  const std::string& publickey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_publickey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_publickey();
  PROTOBUF_NODISCARD std::string* release_publickey();
  void set_allocated_publickey(std::string* publickey);
  private:
  const std::string& _internal_publickey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_publickey(const std::string& value);
  std::string* _internal_mutable_publickey();
  public:

  // required .legacy_pb.Certificate.Version version = 1;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  ::legacy_pb::Certificate_Version version() const;
  void set_version(::legacy_pb::Certificate_Version value);
  private:
  ::legacy_pb::Certificate_Version _internal_version() const;
  void _internal_set_version(::legacy_pb::Certificate_Version value);
  public:

  // required .legacy_pb.KeyType keyType = 2;
  bool has_keytype() const;
  private:
  bool _internal_has_keytype() const;
  public:
  void clear_keytype();
  ::legacy_pb::KeyType keytype() const;
  void set_keytype(::legacy_pb::KeyType value);
  private:
  ::legacy_pb::KeyType _internal_keytype() const;
  void _internal_set_keytype(::legacy_pb::KeyType value);
  public:

  // @@protoc_insertion_point(class_scope:legacy_pb.Certificate)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publickey_;
  int version_;
  int keytype_;
  friend struct ::TableStruct_certificate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Certificate

// required .legacy_pb.Certificate.Version version = 1;
inline bool Certificate::_internal_has_version() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Certificate::has_version() const {
  return _internal_has_version();
}
inline void Certificate::clear_version() {
  version_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::legacy_pb::Certificate_Version Certificate::_internal_version() const {
  return static_cast< ::legacy_pb::Certificate_Version >(version_);
}
inline ::legacy_pb::Certificate_Version Certificate::version() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Certificate.version)
  return _internal_version();
}
inline void Certificate::_internal_set_version(::legacy_pb::Certificate_Version value) {
  assert(::legacy_pb::Certificate_Version_IsValid(value));
  _has_bits_[0] |= 0x00000002u;
  version_ = value;
}
inline void Certificate::set_version(::legacy_pb::Certificate_Version value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:legacy_pb.Certificate.version)
}

// required .legacy_pb.KeyType keyType = 2;
inline bool Certificate::_internal_has_keytype() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Certificate::has_keytype() const {
  return _internal_has_keytype();
}
inline void Certificate::clear_keytype() {
  keytype_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::legacy_pb::KeyType Certificate::_internal_keytype() const {
  return static_cast< ::legacy_pb::KeyType >(keytype_);
}
inline ::legacy_pb::KeyType Certificate::keytype() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Certificate.keyType)
  return _internal_keytype();
}
inline void Certificate::_internal_set_keytype(::legacy_pb::KeyType value) {
  assert(::legacy_pb::KeyType_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  keytype_ = value;
}
inline void Certificate::set_keytype(::legacy_pb::KeyType value) {
  _internal_set_keytype(value);
  // @@protoc_insertion_point(field_set:legacy_pb.Certificate.keyType)
}

// required bytes publicKey = 4;
inline bool Certificate::_internal_has_publickey() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Certificate::has_publickey() const {
  return _internal_has_publickey();
}
inline void Certificate::clear_publickey() {
  publickey_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Certificate::publickey() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Certificate.publicKey)
  return _internal_publickey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Certificate::set_publickey(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 publickey_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:legacy_pb.Certificate.publicKey)
}
inline std::string* Certificate::mutable_publickey() {
  std::string* _s = _internal_mutable_publickey();
  // @@protoc_insertion_point(field_mutable:legacy_pb.Certificate.publicKey)
  return _s;
}
inline const std::string& Certificate::_internal_publickey() const {
  return publickey_.Get();
}
inline void Certificate::_internal_set_publickey(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  publickey_.Set(value, GetArenaForAllocation());
}
inline std::string* Certificate::_internal_mutable_publickey() {
  _has_bits_[0] |= 0x00000001u;
  return publickey_.Mutable(GetArenaForAllocation());
}
inline std::string* Certificate::release_publickey() {
  // @@protoc_insertion_point(field_release:legacy_pb.Certificate.publicKey)
  if (!_internal_has_publickey()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = publickey_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (publickey_.IsDefault()) {
    publickey_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Certificate::set_allocated_publickey(std::string* publickey) {
  if (publickey != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  publickey_.SetAllocated(publickey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (publickey_.IsDefault()) {
    publickey_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:legacy_pb.Certificate.publicKey)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace legacy_pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::legacy_pb::Certificate_Version> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::legacy_pb::Certificate_Version>() {
  return ::legacy_pb::Certificate_Version_descriptor();
}
template <> struct is_proto_enum< ::legacy_pb::KeyType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::legacy_pb::KeyType>() {
  return ::legacy_pb::KeyType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_certificate_2eproto
