// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: legacy_claim.proto

#include "legacy_claim.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace legacy_pb {
PROTOBUF_CONSTEXPR Claim::Claim(
    ::_pbi::ConstantInitialized)
  : stream_(nullptr)
  , certificate_(nullptr)
  , publishersignature_(nullptr)
  , version_(0)

  , claimtype_(0)
{}
struct ClaimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClaimDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClaimDefaultTypeInternal() {}
  union {
    Claim _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClaimDefaultTypeInternal _Claim_default_instance_;
}  // namespace legacy_pb
static ::_pb::Metadata file_level_metadata_legacy_5fclaim_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_legacy_5fclaim_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_legacy_5fclaim_2eproto = nullptr;

const uint32_t TableStruct_legacy_5fclaim_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, version_),
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, claimtype_),
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, stream_),
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, certificate_),
  PROTOBUF_FIELD_OFFSET(::legacy_pb::Claim, publishersignature_),
  3,
  4,
  0,
  1,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, -1, sizeof(::legacy_pb::Claim)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::legacy_pb::_Claim_default_instance_._instance,
};

const char descriptor_table_protodef_legacy_5fclaim_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022legacy_claim.proto\022\tlegacy_pb\032\014stream."
  "proto\032\021certificate.proto\032\017signature.prot"
  "o\"\331\002\n\005Claim\022)\n\007version\030\001 \002(\0162\030.legacy_pb"
  ".Claim.Version\022-\n\tclaimType\030\002 \002(\0162\032.lega"
  "cy_pb.Claim.ClaimType\022!\n\006stream\030\003 \001(\0132\021."
  "legacy_pb.Stream\022+\n\013certificate\030\004 \001(\0132\026."
  "legacy_pb.Certificate\0220\n\022publisherSignat"
  "ure\030\005 \001(\0132\024.legacy_pb.Signature\"*\n\007Versi"
  "on\022\023\n\017UNKNOWN_VERSION\020\000\022\n\n\006_0_0_1\020\001\"H\n\tC"
  "laimType\022\026\n\022UNKNOWN_CLAIM_TYPE\020\000\022\016\n\nstre"
  "amType\020\001\022\023\n\017certificateType\020\002"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_legacy_5fclaim_2eproto_deps[3] = {
  &::descriptor_table_certificate_2eproto,
  &::descriptor_table_signature_2eproto,
  &::descriptor_table_stream_2eproto,
};
static ::_pbi::once_flag descriptor_table_legacy_5fclaim_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_legacy_5fclaim_2eproto = {
    false, false, 429, descriptor_table_protodef_legacy_5fclaim_2eproto,
    "legacy_claim.proto",
    &descriptor_table_legacy_5fclaim_2eproto_once, descriptor_table_legacy_5fclaim_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_legacy_5fclaim_2eproto::offsets,
    file_level_metadata_legacy_5fclaim_2eproto, file_level_enum_descriptors_legacy_5fclaim_2eproto,
    file_level_service_descriptors_legacy_5fclaim_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_legacy_5fclaim_2eproto_getter() {
  return &descriptor_table_legacy_5fclaim_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_legacy_5fclaim_2eproto(&descriptor_table_legacy_5fclaim_2eproto);
namespace legacy_pb {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Claim_Version_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_legacy_5fclaim_2eproto);
  return file_level_enum_descriptors_legacy_5fclaim_2eproto[0];
}
bool Claim_Version_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Claim_Version Claim::UNKNOWN_VERSION;
constexpr Claim_Version Claim::_0_0_1;
constexpr Claim_Version Claim::Version_MIN;
constexpr Claim_Version Claim::Version_MAX;
constexpr int Claim::Version_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Claim_ClaimType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_legacy_5fclaim_2eproto);
  return file_level_enum_descriptors_legacy_5fclaim_2eproto[1];
}
bool Claim_ClaimType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Claim_ClaimType Claim::UNKNOWN_CLAIM_TYPE;
constexpr Claim_ClaimType Claim::streamType;
constexpr Claim_ClaimType Claim::certificateType;
constexpr Claim_ClaimType Claim::ClaimType_MIN;
constexpr Claim_ClaimType Claim::ClaimType_MAX;
constexpr int Claim::ClaimType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Claim::_Internal {
 public:
  using HasBits = decltype(std::declval<Claim>()._has_bits_);
  static void set_has_version(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_claimtype(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::legacy_pb::Stream& stream(const Claim* msg);
  static void set_has_stream(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::legacy_pb::Certificate& certificate(const Claim* msg);
  static void set_has_certificate(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::legacy_pb::Signature& publishersignature(const Claim* msg);
  static void set_has_publishersignature(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000018) ^ 0x00000018) != 0;
  }
};

const ::legacy_pb::Stream&
Claim::_Internal::stream(const Claim* msg) {
  return *msg->stream_;
}
const ::legacy_pb::Certificate&
Claim::_Internal::certificate(const Claim* msg) {
  return *msg->certificate_;
}
const ::legacy_pb::Signature&
Claim::_Internal::publishersignature(const Claim* msg) {
  return *msg->publishersignature_;
}
void Claim::clear_stream() {
  if (stream_ != nullptr) stream_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void Claim::clear_certificate() {
  if (certificate_ != nullptr) certificate_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void Claim::clear_publishersignature() {
  if (publishersignature_ != nullptr) publishersignature_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
Claim::Claim(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:legacy_pb.Claim)
}
Claim::Claim(const Claim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_stream()) {
    stream_ = new ::legacy_pb::Stream(*from.stream_);
  } else {
    stream_ = nullptr;
  }
  if (from._internal_has_certificate()) {
    certificate_ = new ::legacy_pb::Certificate(*from.certificate_);
  } else {
    certificate_ = nullptr;
  }
  if (from._internal_has_publishersignature()) {
    publishersignature_ = new ::legacy_pb::Signature(*from.publishersignature_);
  } else {
    publishersignature_ = nullptr;
  }
  ::memcpy(&version_, &from.version_,
    static_cast<size_t>(reinterpret_cast<char*>(&claimtype_) -
    reinterpret_cast<char*>(&version_)) + sizeof(claimtype_));
  // @@protoc_insertion_point(copy_constructor:legacy_pb.Claim)
}

inline void Claim::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&stream_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&claimtype_) -
    reinterpret_cast<char*>(&stream_)) + sizeof(claimtype_));
}

Claim::~Claim() {
  // @@protoc_insertion_point(destructor:legacy_pb.Claim)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Claim::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete stream_;
  if (this != internal_default_instance()) delete certificate_;
  if (this != internal_default_instance()) delete publishersignature_;
}

void Claim::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Claim::Clear() {
// @@protoc_insertion_point(message_clear_start:legacy_pb.Claim)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(stream_ != nullptr);
      stream_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(certificate_ != nullptr);
      certificate_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(publishersignature_ != nullptr);
      publishersignature_->Clear();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&version_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&claimtype_) -
        reinterpret_cast<char*>(&version_)) + sizeof(claimtype_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Claim::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .legacy_pb.Claim.Version version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::legacy_pb::Claim_Version_IsValid(val))) {
            _internal_set_version(static_cast<::legacy_pb::Claim_Version>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required .legacy_pb.Claim.ClaimType claimType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::legacy_pb::Claim_ClaimType_IsValid(val))) {
            _internal_set_claimtype(static_cast<::legacy_pb::Claim_ClaimType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // optional .legacy_pb.Stream stream = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_stream(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .legacy_pb.Certificate certificate = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_certificate(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .legacy_pb.Signature publisherSignature = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_publishersignature(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Claim::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:legacy_pb.Claim)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .legacy_pb.Claim.Version version = 1;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_version(), target);
  }

  // required .legacy_pb.Claim.ClaimType claimType = 2;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_claimtype(), target);
  }

  // optional .legacy_pb.Stream stream = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::stream(this),
        _Internal::stream(this).GetCachedSize(), target, stream);
  }

  // optional .legacy_pb.Certificate certificate = 4;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::certificate(this),
        _Internal::certificate(this).GetCachedSize(), target, stream);
  }

  // optional .legacy_pb.Signature publisherSignature = 5;
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::publishersignature(this),
        _Internal::publishersignature(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:legacy_pb.Claim)
  return target;
}

size_t Claim::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:legacy_pb.Claim)
  size_t total_size = 0;

  if (_internal_has_version()) {
    // required .legacy_pb.Claim.Version version = 1;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_version());
  }

  if (_internal_has_claimtype()) {
    // required .legacy_pb.Claim.ClaimType claimType = 2;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_claimtype());
  }

  return total_size;
}
size_t Claim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:legacy_pb.Claim)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000018) ^ 0x00000018) == 0) {  // All required fields are present.
    // required .legacy_pb.Claim.Version version = 1;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_version());

    // required .legacy_pb.Claim.ClaimType claimType = 2;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_claimtype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional .legacy_pb.Stream stream = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *stream_);
    }

    // optional .legacy_pb.Certificate certificate = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *certificate_);
    }

    // optional .legacy_pb.Signature publisherSignature = 5;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *publishersignature_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Claim::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Claim::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Claim::GetClassData() const { return &_class_data_; }

void Claim::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Claim *>(to)->MergeFrom(
      static_cast<const Claim &>(from));
}


void Claim::MergeFrom(const Claim& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:legacy_pb.Claim)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_stream()->::legacy_pb::Stream::MergeFrom(from._internal_stream());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_certificate()->::legacy_pb::Certificate::MergeFrom(from._internal_certificate());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_publishersignature()->::legacy_pb::Signature::MergeFrom(from._internal_publishersignature());
    }
    if (cached_has_bits & 0x00000008u) {
      version_ = from.version_;
    }
    if (cached_has_bits & 0x00000010u) {
      claimtype_ = from.claimtype_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Claim::CopyFrom(const Claim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:legacy_pb.Claim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Claim::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_stream()) {
    if (!stream_->IsInitialized()) return false;
  }
  if (_internal_has_certificate()) {
    if (!certificate_->IsInitialized()) return false;
  }
  if (_internal_has_publishersignature()) {
    if (!publishersignature_->IsInitialized()) return false;
  }
  return true;
}

void Claim::InternalSwap(Claim* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Claim, claimtype_)
      + sizeof(Claim::claimtype_)
      - PROTOBUF_FIELD_OFFSET(Claim, stream_)>(
          reinterpret_cast<char*>(&stream_),
          reinterpret_cast<char*>(&other->stream_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Claim::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_legacy_5fclaim_2eproto_getter, &descriptor_table_legacy_5fclaim_2eproto_once,
      file_level_metadata_legacy_5fclaim_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace legacy_pb
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::legacy_pb::Claim*
Arena::CreateMaybeMessage< ::legacy_pb::Claim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::legacy_pb::Claim >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
