// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: source.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_source_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_source_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_source_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_source_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_source_2eproto;
namespace legacy_pb {
class Source;
struct SourceDefaultTypeInternal;
extern SourceDefaultTypeInternal _Source_default_instance_;
}  // namespace legacy_pb
PROTOBUF_NAMESPACE_OPEN
template<> ::legacy_pb::Source* Arena::CreateMaybeMessage<::legacy_pb::Source>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace legacy_pb {

enum Source_Version : int {
  Source_Version_UNKNOWN_VERSION = 0,
  Source_Version__0_0_1 = 1
};
bool Source_Version_IsValid(int value);
constexpr Source_Version Source_Version_Version_MIN = Source_Version_UNKNOWN_VERSION;
constexpr Source_Version Source_Version_Version_MAX = Source_Version__0_0_1;
constexpr int Source_Version_Version_ARRAYSIZE = Source_Version_Version_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Source_Version_descriptor();
template<typename T>
inline const std::string& Source_Version_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Source_Version>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Source_Version_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Source_Version_descriptor(), enum_t_value);
}
inline bool Source_Version_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Source_Version* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Source_Version>(
    Source_Version_descriptor(), name, value);
}
enum Source_SourceTypes : int {
  Source_SourceTypes_UNKNOWN_SOURCE_TYPE = 0,
  Source_SourceTypes_lbry_sd_hash = 1
};
bool Source_SourceTypes_IsValid(int value);
constexpr Source_SourceTypes Source_SourceTypes_SourceTypes_MIN = Source_SourceTypes_UNKNOWN_SOURCE_TYPE;
constexpr Source_SourceTypes Source_SourceTypes_SourceTypes_MAX = Source_SourceTypes_lbry_sd_hash;
constexpr int Source_SourceTypes_SourceTypes_ARRAYSIZE = Source_SourceTypes_SourceTypes_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Source_SourceTypes_descriptor();
template<typename T>
inline const std::string& Source_SourceTypes_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Source_SourceTypes>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Source_SourceTypes_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Source_SourceTypes_descriptor(), enum_t_value);
}
inline bool Source_SourceTypes_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Source_SourceTypes* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Source_SourceTypes>(
    Source_SourceTypes_descriptor(), name, value);
}
// ===================================================================

class Source final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:legacy_pb.Source) */ {
 public:
  inline Source() : Source(nullptr) {}
  ~Source() override;
  explicit PROTOBUF_CONSTEXPR Source(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Source(const Source& from);
  Source(Source&& from) noexcept
    : Source() {
    *this = ::std::move(from);
  }

  inline Source& operator=(const Source& from) {
    CopyFrom(from);
    return *this;
  }
  inline Source& operator=(Source&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Source& default_instance() {
    return *internal_default_instance();
  }
  static inline const Source* internal_default_instance() {
    return reinterpret_cast<const Source*>(
               &_Source_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Source& a, Source& b) {
    a.Swap(&b);
  }
  inline void Swap(Source* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Source* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Source* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Source>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Source& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Source& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Source* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "legacy_pb.Source";
  }
  protected:
  explicit Source(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Source_Version Version;
  static constexpr Version UNKNOWN_VERSION =
    Source_Version_UNKNOWN_VERSION;
  static constexpr Version _0_0_1 =
    Source_Version__0_0_1;
  static inline bool Version_IsValid(int value) {
    return Source_Version_IsValid(value);
  }
  static constexpr Version Version_MIN =
    Source_Version_Version_MIN;
  static constexpr Version Version_MAX =
    Source_Version_Version_MAX;
  static constexpr int Version_ARRAYSIZE =
    Source_Version_Version_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Version_descriptor() {
    return Source_Version_descriptor();
  }
  template<typename T>
  static inline const std::string& Version_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Version>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Version_Name.");
    return Source_Version_Name(enum_t_value);
  }
  static inline bool Version_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Version* value) {
    return Source_Version_Parse(name, value);
  }

  typedef Source_SourceTypes SourceTypes;
  static constexpr SourceTypes UNKNOWN_SOURCE_TYPE =
    Source_SourceTypes_UNKNOWN_SOURCE_TYPE;
  static constexpr SourceTypes lbry_sd_hash =
    Source_SourceTypes_lbry_sd_hash;
  static inline bool SourceTypes_IsValid(int value) {
    return Source_SourceTypes_IsValid(value);
  }
  static constexpr SourceTypes SourceTypes_MIN =
    Source_SourceTypes_SourceTypes_MIN;
  static constexpr SourceTypes SourceTypes_MAX =
    Source_SourceTypes_SourceTypes_MAX;
  static constexpr int SourceTypes_ARRAYSIZE =
    Source_SourceTypes_SourceTypes_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  SourceTypes_descriptor() {
    return Source_SourceTypes_descriptor();
  }
  template<typename T>
  static inline const std::string& SourceTypes_Name(T enum_t_value) {
    static_assert(::std::is_same<T, SourceTypes>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function SourceTypes_Name.");
    return Source_SourceTypes_Name(enum_t_value);
  }
  static inline bool SourceTypes_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      SourceTypes* value) {
    return Source_SourceTypes_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSourceFieldNumber = 3,
    kContentTypeFieldNumber = 4,
    kVersionFieldNumber = 1,
    kSourceTypeFieldNumber = 2,
  };
  // required bytes source = 3;
  bool has_source() const;
  private:
  bool _internal_has_source() const;
  public:
  void clear_source();
  const std::string& source() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_source(ArgT0&& arg0, ArgT... args);
  std::string* mutable_source();
  PROTOBUF_NODISCARD std::string* release_source();
  void set_allocated_source(std::string* source);
  private:
  const std::string& _internal_source() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source(const std::string& value);
  std::string* _internal_mutable_source();
  public:

  // required string contentType = 4;
  bool has_contenttype() const;
  private:
  bool _internal_has_contenttype() const;
  public:
  void clear_contenttype();
  const std::string& contenttype() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_contenttype(ArgT0&& arg0, ArgT... args);
  std::string* mutable_contenttype();
  PROTOBUF_NODISCARD std::string* release_contenttype();
  void set_allocated_contenttype(std::string* contenttype);
  private:
  const std::string& _internal_contenttype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_contenttype(const std::string& value);
  std::string* _internal_mutable_contenttype();
  public:

  // required .legacy_pb.Source.Version version = 1;
  bool has_version() const;
  private:
  bool _internal_has_version() const;
  public:
  void clear_version();
  ::legacy_pb::Source_Version version() const;
  void set_version(::legacy_pb::Source_Version value);
  private:
  ::legacy_pb::Source_Version _internal_version() const;
  void _internal_set_version(::legacy_pb::Source_Version value);
  public:

  // required .legacy_pb.Source.SourceTypes sourceType = 2;
  bool has_sourcetype() const;
  private:
  bool _internal_has_sourcetype() const;
  public:
  void clear_sourcetype();
  ::legacy_pb::Source_SourceTypes sourcetype() const;
  void set_sourcetype(::legacy_pb::Source_SourceTypes value);
  private:
  ::legacy_pb::Source_SourceTypes _internal_sourcetype() const;
  void _internal_set_sourcetype(::legacy_pb::Source_SourceTypes value);
  public:

  // @@protoc_insertion_point(class_scope:legacy_pb.Source)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr source_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr contenttype_;
  int version_;
  int sourcetype_;
  friend struct ::TableStruct_source_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Source

// required .legacy_pb.Source.Version version = 1;
inline bool Source::_internal_has_version() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Source::has_version() const {
  return _internal_has_version();
}
inline void Source::clear_version() {
  version_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::legacy_pb::Source_Version Source::_internal_version() const {
  return static_cast< ::legacy_pb::Source_Version >(version_);
}
inline ::legacy_pb::Source_Version Source::version() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Source.version)
  return _internal_version();
}
inline void Source::_internal_set_version(::legacy_pb::Source_Version value) {
  assert(::legacy_pb::Source_Version_IsValid(value));
  _has_bits_[0] |= 0x00000004u;
  version_ = value;
}
inline void Source::set_version(::legacy_pb::Source_Version value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:legacy_pb.Source.version)
}

// required .legacy_pb.Source.SourceTypes sourceType = 2;
inline bool Source::_internal_has_sourcetype() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Source::has_sourcetype() const {
  return _internal_has_sourcetype();
}
inline void Source::clear_sourcetype() {
  sourcetype_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::legacy_pb::Source_SourceTypes Source::_internal_sourcetype() const {
  return static_cast< ::legacy_pb::Source_SourceTypes >(sourcetype_);
}
inline ::legacy_pb::Source_SourceTypes Source::sourcetype() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Source.sourceType)
  return _internal_sourcetype();
}
inline void Source::_internal_set_sourcetype(::legacy_pb::Source_SourceTypes value) {
  assert(::legacy_pb::Source_SourceTypes_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  sourcetype_ = value;
}
inline void Source::set_sourcetype(::legacy_pb::Source_SourceTypes value) {
  _internal_set_sourcetype(value);
  // @@protoc_insertion_point(field_set:legacy_pb.Source.sourceType)
}

// required bytes source = 3;
inline bool Source::_internal_has_source() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Source::has_source() const {
  return _internal_has_source();
}
inline void Source::clear_source() {
  source_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Source::source() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Source.source)
  return _internal_source();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Source::set_source(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 source_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:legacy_pb.Source.source)
}
inline std::string* Source::mutable_source() {
  std::string* _s = _internal_mutable_source();
  // @@protoc_insertion_point(field_mutable:legacy_pb.Source.source)
  return _s;
}
inline const std::string& Source::_internal_source() const {
  return source_.Get();
}
inline void Source::_internal_set_source(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  source_.Set(value, GetArenaForAllocation());
}
inline std::string* Source::_internal_mutable_source() {
  _has_bits_[0] |= 0x00000001u;
  return source_.Mutable(GetArenaForAllocation());
}
inline std::string* Source::release_source() {
  // @@protoc_insertion_point(field_release:legacy_pb.Source.source)
  if (!_internal_has_source()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = source_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (source_.IsDefault()) {
    source_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Source::set_allocated_source(std::string* source) {
  if (source != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  source_.SetAllocated(source, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (source_.IsDefault()) {
    source_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:legacy_pb.Source.source)
}

// required string contentType = 4;
inline bool Source::_internal_has_contenttype() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Source::has_contenttype() const {
  return _internal_has_contenttype();
}
inline void Source::clear_contenttype() {
  contenttype_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Source::contenttype() const {
  // @@protoc_insertion_point(field_get:legacy_pb.Source.contentType)
  return _internal_contenttype();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Source::set_contenttype(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 contenttype_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:legacy_pb.Source.contentType)
}
inline std::string* Source::mutable_contenttype() {
  std::string* _s = _internal_mutable_contenttype();
  // @@protoc_insertion_point(field_mutable:legacy_pb.Source.contentType)
  return _s;
}
inline const std::string& Source::_internal_contenttype() const {
  return contenttype_.Get();
}
inline void Source::_internal_set_contenttype(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  contenttype_.Set(value, GetArenaForAllocation());
}
inline std::string* Source::_internal_mutable_contenttype() {
  _has_bits_[0] |= 0x00000002u;
  return contenttype_.Mutable(GetArenaForAllocation());
}
inline std::string* Source::release_contenttype() {
  // @@protoc_insertion_point(field_release:legacy_pb.Source.contentType)
  if (!_internal_has_contenttype()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = contenttype_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (contenttype_.IsDefault()) {
    contenttype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Source::set_allocated_contenttype(std::string* contenttype) {
  if (contenttype != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  contenttype_.SetAllocated(contenttype, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (contenttype_.IsDefault()) {
    contenttype_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:legacy_pb.Source.contentType)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace legacy_pb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::legacy_pb::Source_Version> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::legacy_pb::Source_Version>() {
  return ::legacy_pb::Source_Version_descriptor();
}
template <> struct is_proto_enum< ::legacy_pb::Source_SourceTypes> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::legacy_pb::Source_SourceTypes>() {
  return ::legacy_pb::Source_SourceTypes_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_source_2eproto
